### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by tianjiahao** [NieXC/pytorch-pil#2]
myubuntu@myubuntu-Precision-WorkStation-T5500:~/Music/pytorch-pil$ sh run_train.sh
Human Pose Estimation with Parsing Induced Learner: [Train and Val Phase]
Loading training json file: dataset/lip/jsons/LIP_SP_TRAIN_annotations.json...
Finished loading training json file
Loading evaluation json file: dataset/lip/jsons/LIP_SP_VAL_annotations.json...
Finished loading evaluation json file
Traceback (most recent call last):
  File "main.py", line 394, in <module>
    main()
  File "main.py", line 166, in main
    train(train_loader, hpe_with_pil_net, pose_criterion, parsing_criterion, optimizer, epoch)
  File "main.py", line 222, in train
    for i, (im, pose_target, parsing_target) in enumerate(train_loader):
  File "/home/myubuntu/anaconda3/envs/pytorch-PIL/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/home/myubuntu/anaconda3/envs/pytorch-PIL/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/myubuntu/anaconda3/envs/pytorch-PIL/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/myubuntu/anaconda3/envs/pytorch-PIL/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 40, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/myubuntu/Music/pytorch-pil/utils/data_loader.py", line 136, in __getitem__
    pose_target = target_gen.gen_pose_target(flipped_joints, visibility, self.pose_net_stride, grid_x, grid_y, self.sigma)
  File "/home/myubuntu/Music/pytorch-pil/utils/target_generation.py", line 48, in gen_pose_target
    gaussian_maps = np.zeros((joint_num + 1, grid_y, grid_x))
TypeError: 'float' object cannot be interpreted as an integer
should I ｍodify ｉｔ in the source code？ how to solve this problem?

**Comment by gaoyao123** [comment]
grid_y and grid_x are float numbers,so you must transform them into integer by int().You can use pdb.set_trace() to verify it.
